name: Deploy to Heroku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Heroku Container Registry
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

    - name: Build the Docker image
      run: |
        docker build -t registry.heroku.com/spacexapp/web .

    - name: Push Docker image to Heroku
      run: |
        docker push registry.heroku.com/spacexapp/web

    - name: Release the app on Heroku
      run: |
        heroku container:release web --app spacexapp

    - name: Clean up
      run: |
        docker logout
